Trim trailing end slashes (and fix formatting)
enviodev/hyperindex pull request #164
Opened 2024-08-30 16:54 UTC by JasoonS

2024-08-30 16:54 UTC, JasoonS commented on codegenerator/cli/src/config_parsing/system_config.rs
> +              Ok(Self::HypersyncConfig(HypersyncConfig { endpoint_url: trimmed_url, is_client_decoder }))
These 3 lines are the only changes, Everything else is just formatting (indentation was wrong)

2024-08-30 17:04 UTC, JasoonS commented on codegenerator/cli/src/config_parsing/system_config.rs
> +    fn test_hypersync_url_trailing_slash_trimming() {
Decided to add a small test for good measure

2024-09-02 07:22 UTC, DZakh requested changes
Nitpick: In this case I'd replace the `validate_url` function with the `parse_url` one, which would either return None, or Some with trimmed URL. Also, looks like we'd like to have the same logic for rpc URLs, not only hypersync

2024-09-02 07:55 UTC, DZakh reviewed
Since you're away, I've done the change myself. @JonoPrest Could you review, please

2024-09-02 08:13 UTC, JonoPrest approved these changes
LFG

2024-09-02 08:27 UTC, DZakh approved these changes

2024-09-02 08:31 UTC, merged