Allow to freely adjust the config type
enviodev/hyperindex pull request #368
Opened 2024-11-28 15:54 UTC by DZakh

Previously, it wouldn't be possible, because the config type was exposed via the `getGeneratedByChainId`. This required us to maintain irrelevant code for backward compatibility. I specifically had problems with the `syncSource` which ideally should be deprecated in favor of chain workers (sources).
So I turned the `ConfigYAML` to a separate handlebar template to allow us change the config type however we want. This is also a step towards making the config to be a more user-facing interface of the library.

2024-11-28 16:29 UTC, JonoPrest commented on codegenerator/cli/templates/dynamic/codegen/src/ConfigYAML.res.hbs
> +  syncConfig: Config.syncConfig,
Why is that a regression out of interest? Do you just mean that it doesn't maintain backwards compatibility?

2024-11-28 16:34 UTC, JonoPrest commented on codegenerator/cli/templates/static/codegen/src/eventFetching/chainWorkers/RpcWorker.res
> -        Pervasives.min(finalExecutedBlockInterval + sc.accelerationAdditive, sc.intervalCeiling),
What do you mean? I don't see this being done in the function mentioned?

2024-11-28 16:50 UTC, JonoPrest requested changes
Hey @DZakh, I'm not sure about how you're handling the block range interval when removing the setting of "currentInterval" lets chat and figure that out first.

2024-11-28 16:53 UTC, DZakh commented on codegenerator/cli/templates/static/codegen/src/eventFetching/chainWorkers/RpcWorker.res
> -        Pervasives.min(finalExecutedBlockInterval + sc.accelerationAdditive, sc.intervalCeiling),
It's here https://github.com/enviodev/hyperindex/blob/71cfc01a83c4aa3e571c925b16518750fa94e1bd/codegenerator/cli/templates/static/codegen/src/EventFetching.res#L307-L310

2024-11-28 16:54 UTC, DZakh commented on codegenerator/cli/templates/dynamic/codegen/src/ConfigYAML.res.hbs
> +  syncConfig: Config.syncConfig,
Yeah. Even though it wasn't exposed via genType, the provider value was still present before the change. Now it doesn't. Theoretically someone could use it, but there's a really tiny chance for this.

2024-11-29 09:43 UTC, JonoPrest commented on codegenerator/cli/templates/static/codegen/src/eventFetching/chainWorkers/RpcWorker.res
> -        Pervasives.min(finalExecutedBlockInterval + sc.accelerationAdditive, sc.intervalCeiling),
I see that... but it's different code. Otherwise there is no persistence of the last interval used between calls to the chain worker.

2024-11-29 09:46 UTC, DZakh commented on codegenerator/cli/templates/static/codegen/src/eventFetching/chainWorkers/RpcWorker.res
> -        Pervasives.min(finalExecutedBlockInterval + sc.accelerationAdditive, sc.intervalCeiling),
The code is persisted as a `finalExecutedBlockInterval`

2024-11-29 09:47 UTC, JonoPrest commented on codegenerator/cli/templates/static/codegen/src/eventFetching/chainWorkers/RpcWorker.res
> -        Pervasives.min(finalExecutedBlockInterval + sc.accelerationAdditive, sc.intervalCeiling),
It's not persisted, that's a ref in the scope of the calling function

2024-11-29 13:34 UTC, JonoPrest approved these changes
All good 😄👍🏼 sorry for the misunderstanding

2024-11-29 14:04 UTC, merged